language: node_js
node_js:
  - '8'
cache: yarn
script:
  - yarn run test
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  keep-history: true
  local-dir: build
