language: node_js
node_js:
  - '8'
cache: yarn
script:
  - yarn run test
  - yarn build
deploy:
  provider: script
  skip-cleanup: true
  script:
    - yarn run predeploy
    - yarn run deploy
  on:
    branch: master
